// Sonuç ekranında gösterilen kısa kelime açıklamaları.
// Bu proje için yazıldı; TDK sözlüğünden alıntı değildir. Açıklaması olmayan kelimeler
// için sonuç ekranı TDK sözlüğüne bağlantı verir.

export const MEANINGS = {
  KABLO: 'Elektrik ya da sinyal taşıyan, dışı yalıtılmış tel demeti.',
  KALEM: 'Yazı yazmaya ya da çizim yapmaya yarayan araç.',
  KİTAP: 'Ciltlenmiş, basılı sayfalardan oluşan eser.',
  MASAL: 'Olağanüstü olayları anlatan, çoğunlukla sözlü gelenekten gelen hikâye.',
  ELMAS: 'Karbonun kristal hâli; bilinen en sert doğal madde ve değerli bir taş.',
  YAZAR: 'Kitap, makale gibi eserler yazan kimse.',
  ÇİÇEK: 'Bitkilerin üremeyi sağlayan, çoğunlukla renkli ve kokulu organı.',
  SABAH: 'Günün, güneşin doğuşundan öğleye kadar süren bölümü.',
  AKŞAM: 'Günün, güneşin batışından gece karanlığına kadar süren bölümü.',
  BULUT: 'Havada asılı duran su damlacıkları ya da buz kristallerinden oluşan küme.',
  DENİZ: 'Karalar arasında kalan geniş tuzlu su kütlesi.',
  ORMAN: 'Ağaçların sık biçimde bir arada bulunduğu geniş alan.',
  BAHÇE: 'Çiçek, sebze ya da ağaç yetiştirilen, çoğunlukla çevrili yer.',
  KAPAK: 'Bir kabın ya da kutunun ağzını örten parça.',
  KÖPEK: 'Bekçilik ve arkadaşlık için beslenen, evcilleştirilmiş hayvan.',
  KUZEY: 'Dört ana yönden biri; güneyin karşıtı.',
  GÜNEY: 'Dört ana yönden biri; kuzeyin karşıtı.',
  ŞEHİR: 'Kalabalık nüfuslu, yönetim ve ticaret merkezi olan büyük yerleşim yeri.',
  KÖPRÜ: 'Bir akarsuyun, vadinin ya da yolun iki yakasını birleştiren yapı.',
  KUMAŞ: 'İplikten dokunan, giysi yapımında kullanılan malzeme.',
  DOLAP: 'Eşya konulan, kapaklı ve raflı mobilya.',
  SEHPA: 'Üzerine bir şey konulan alçak, küçük masa.',
  TABAK: 'Yemek konulan yayvan kap.',
  ÇATAL: 'Yemek yerken kullanılan, uçları dişli araç.',
  KAŞIK: 'Sıvı ya da yumuşak yiyecekleri ağza götürmeye yarayan araç.',
  BIÇAK: 'Kesmeye yarayan, saplı ve keskin ağızlı araç.',
  TAVUK: 'Eti ve yumurtası için beslenen kümes hayvanı.',
  ASLAN: 'Kedigillerden, erkeğinin yelesiyle tanınan iri yırtıcı.',
  TİLKİ: 'Kızıl tüylü, sivri burunlu, gür kuyruklu yabani hayvan.',
  ARMUT: 'Armut ağacının sulu ve tatlı meyvesi.',
  KAVUN: 'Kabakgillerden, yazın yetişen tatlı ve kokulu meyve.',
  KİRAZ: 'Kırmızı, küçük, çekirdekli bir yaz meyvesi.',
  LİMON: 'Ekşi suyu olan, sarı kabuklu turunçgil.',
  HAVUÇ: 'Turuncu renkli, uzun kökü yenen sebze.',
  SOĞAN: 'Keskin kokulu, katmanlı yumru sebze.',
  BİBER: 'Acı ya da tatlı türleri olan, yemeklere tat veren sebze.',
  EKMEK: 'Unun mayalanıp pişirilmesiyle yapılan temel besin.',
  ŞEKER: 'Şeker pancarı ya da kamışından elde edilen tatlandırıcı.',
  ÇORBA: 'Sulu pişirilen, çoğunlukla yemeğe başlarken içilen yemek.',
  KAHVE: 'Kavrulup öğütülmüş kahve çekirdeğinden yapılan içecek.',
  TATİL: 'Çalışmaya ya da okula ara verilen dinlenme dönemi.',
  SINAV: 'Bilgi ve beceriyi ölçmek için yapılan deneme.',
  DÜNYA: 'Üzerinde yaşadığımız gezegen.',
  GÜNEŞ: 'Dünya\'nın çevresinde döndüğü, ısı ve ışık veren yıldız.',
  ROKET: 'Yakıt yakıp gaz püskürterek ilerleyen araç.',
  ARABA: 'Tekerlekli kara taşıtı; otomobil.',
  MOTOR: 'Enerjiyi harekete dönüştüren makine.',
  FENER: 'İçinde ışık kaynağı bulunan, taşınabilir aydınlatma aracı.',
  KİLİT: 'Kapı, çekmece gibi şeyleri kapalı tutan düzenek.',
  DUVAR: 'Bir yeri çevirmek ya da bölmek için örülen dikey yapı.',
  SALON: 'Evlerde misafir ağırlanan geniş oda.',
  YATAK: 'Üzerinde uyunan döşek ya da mobilya.',
  PERDE: 'Pencere ya da sahne önüne gerilen kumaş.',
  LAMBA: 'Işık veren aydınlatma aracı.',
  HAFTA: 'Yedi günlük zaman dilimi.',
  BAHAR: 'Kıştan sonra gelen mevsim; ilkbahar.',
  DALGA: 'Su yüzeyinde rüzgârla oluşan kabarma.',
  YAYLA: 'Dağlık bölgede, yazın çıkılan serin otlak.',
  NEHİR: 'Denize ya da göle dökülen büyük akarsu.',
  IRMAK: 'Denize, göle ya da başka bir akarsuya dökülen büyük akarsu.',
  PINAR: 'Yerden kaynayan su; kaynak.',
  KAYIK: 'Kürekle ya da küçük motorla yürütülen küçük tekne.',
  LİMAN: 'Gemilerin yanaştığı, dalgadan korunaklı kıyı yeri.',
  ÇADIR: 'Kamp yaparken kurulan, kumaştan taşınabilir barınak.',
  GİTAR: 'Telleri parmakla ya da penayla çalınan müzik aleti.',
  DAVUL: 'Tokmakla vurularak çalınan, iki yüzü deri kaplı çalgı.',
  ŞARKI: 'Bir ezgiyle söylenen söz.',
  RESİM: 'Çizgi ve renklerle yapılan görsel eser.',
  SAHNE: 'Tiyatro ve konserlerde gösterinin yapıldığı yükseltilmiş yer.',
  SEVGİ: 'Birine ya da bir şeye karşı duyulan bağlılık ve yakınlık.',
  HAYAL: 'Gerçekte olmayan, zihinde canlandırılan şey.',
  CESUR: 'Korkusuzca davranan, yürekli.',
  NAZİK: 'İnceliğe dikkat eden, kibar.',
  SAKİN: 'Heyecansız, durgun.',
  TEMİZ: 'Kiri ya da lekesi olmayan.',
  GÜZEL: 'Göze ya da kulağa hoş gelen.',
  HIZLI: 'Çabuk hareket eden.',
  YAVAŞ: 'Hızı az olan, ağır.',
  BÜYÜK: 'Boyutu, miktarı ya da önemi fazla olan.',
  KÜÇÜK: 'Boyutu ya da miktarı az olan.',
  DERİN: 'Yüzeyden dibe uzaklığı fazla olan.',
  SICAK: 'Isısı yüksek olan.',
  SOĞUK: 'Isısı düşük olan.',
  TATLI: 'Şeker tadında olan.',
  KOLAY: 'Yapılması güç olmayan.',
  DOĞRU: 'Gerçeğe uygun olan; eğri olmayan.',
  BEYAZ: 'Kar ya da süt renginde olan.',
  SİYAH: 'Kömür renginde olan; kara.',
  YEŞİL: 'Çimen ve yaprak renginde olan.',
  PEMBE: 'Açık kırmızı, gül renginde olan.',
  GÜMÜŞ: 'Parlak beyaz renkli değerli metal.',
  ALTIN: 'Sarı renkli, parlak, değerli metal.',
  DEMİR: 'Sanayide çok kullanılan sert, gri metal.',
  BAKIR: 'Elektriği iyi ileten, kızıl renkli metal.',
  KÖMÜR: 'Yakıt olarak kullanılan kara renkli madde.',
  TUĞLA: 'Kilden yapılıp fırında pişirilen yapı malzemesi.',
  ÇİMEN: 'Sık biten, kısa, yeşil ot.',
  FİDAN: 'Yeni dikilmiş genç ağaç.',
  TOHUM: 'Bitkinin yeniden üremesini sağlayan tane.',
  BÖCEK: 'Altı bacaklı, gövdesi üç bölümlü küçük hayvan.',
  KARGA: 'Kara tüylü, iri gagalı kuş.',
  SERÇE: 'Küçük, kahverengi, şehirlerde yaygın bir kuş.',
  BALIK: 'Suda yaşayan, solungaçla soluyan omurgalı hayvan.',
  YUNUS: 'Denizde yaşayan, zekâsıyla bilinen memeli.',
  ŞAHİN: 'Hızlı uçan, orta boy yırtıcı kuş.',
  ÖRDEK: 'Suda yüzen, yassı gagalı kuş.',
  İNSAN: 'Düşünen ve konuşan canlı; kişi.',
  ÇOCUK: 'Küçük yaşta olan kimse.',
  KOMŞU: 'Yakın evde oturan kimse.',
  TERZİ: 'Giysi diken ya da onaran kimse.',
  HAKEM: 'Maçta kuralları uygulayan kimse.',
  HAYAT: 'Canlının doğumdan ölüme kadar geçirdiği süre; yaşam.',
  ZAMAN: 'Olayların ardı ardına sıralandığı süre.',
  YARIN: 'Bugünden sonraki gün.',
  BUGÜN: 'İçinde bulunulan gün.',
  HABER: 'Bir olay hakkında verilen bilgi.',
  ROMAN: 'Uzun, kurgusal düzyazı eseri.',
  CÜMLE: 'Bir yargıyı bildiren söz dizisi.',
  DİLEK: 'Gerçekleşmesi istenen şey; istek.',
  ZAFER: 'Yarışmada ya da savaşta kazanılan başarı.',
  TENİS: 'Raketle, file üzerinden top atılarak oynanan oyun.',
  YÜZME: 'Suda kol ve bacak hareketleriyle ilerleme sporu.',
  ÇİLEK: 'Kırmızı, küçük, tatlı ve kokulu meyve.',
  BADEM: 'Sert kabuklu, yağlı çekirdek meyve.',
  CEVİZ: 'Sert kabuğunun içinden kıvrımlı bir iç çıkan meyve.',
  PİLAV: 'Pirinç ya da bulgurla yapılan yemek.',
  KEBAP: 'Ateşte ya da fırında pişirilen et yemeği.',
  BÖREK: 'Yufka arasına iç konularak yapılan hamur işi.',
  HELVA: 'Un, şeker ve yağla ya da tahinle yapılan tatlı.',
  AYRAN: 'Yoğurdun suyla çırpılmasıyla yapılan içecek.',
  SALÇA: 'Domates ya da biberden yapılan koyu kıvamlı ezme.',
  MAKAS: 'Kesmeye yarayan, iki ağızlı araç.',
  DÜĞME: 'Giysiyi iliklemeye yarayan küçük parça.',
  CEKET: 'Gömleğin üstüne giyilen, önden açık giysi.',
  ÇANTA: 'Eşya taşımaya yarayan, saplı ya da askılı kap.',
  ŞAPKA: 'Başa giyilen, siperli ya da kenarlı başlık.',
  ÇORAP: 'Ayağa giyilen örme giysi.',
  KEMER: 'Bele takılan kayış; kavisli yapı öğesi.',
  YÜZÜK: 'Parmağa takılan halka biçiminde takı.',
  KOLYE: 'Boyna takılan takı.',
  TARAK: 'Saçı düzeltmeye yarayan dişli araç.',
  SABUN: 'Temizlikte kullanılan, suyla köpüren madde.',
  HAVLU: 'Islanan yeri kurulamaya yarayan kumaş.',
  BİLGİ: 'Öğrenme, araştırma ya da gözlem yoluyla edinilen gerçek.',
  FİKİR: 'Bir konu hakkındaki düşünce; görüş.',
  CEVAP: 'Soruya verilen karşılık; yanıt.',
  ÖRNEK: 'Bir şeyi açıklamak için gösterilen benzeri.',
  KURAL: 'Uyulması gereken ilke.',
  DÜZEN: 'Belli bir sıraya göre olma durumu.',
  HEDEF: 'Ulaşılmak istenen amaç.',
  YOLCU: 'Yolculuk eden kimse.',
  BAVUL: 'Yolculukta eşya taşımaya yarayan büyük çanta.',
  BİLET: 'Taşıta binmek ya da bir yere girmek için alınan belge.',
  DURAK: 'Taşıtların yolcu almak için durduğu yer.',
  SOKAK: 'Evler arasındaki dar yol.',
  CADDE: 'Geniş ve işlek yol.',
  PAZAR: 'Alışveriş yapılan açık alan; haftanın bir günü.',
  ÇARŞI: 'Dükkânların bir arada bulunduğu alışveriş yeri.',
  SARAY: 'Hükümdarların oturduğu büyük yapı.',
  TABLO: 'Çerçevelenmiş resim.',
  ÇİZGİ: 'Kalemle çekilen iz.',
  NOKTA: 'Kalemin kâğıda değdiği yerde kalan küçük iz; cümle sonu işareti.',
  SAYFA: 'Kitap ya da defter yaprağının bir yüzü.',
  SİLGİ: 'Yazıyı silmeye yarayan araç.',
  BEYİN: 'Kafatası içindeki, düşünmeyi ve vücudu yöneten organ.',
  YÜREK: 'Kalp; mecazen cesaret.',
  KULAK: 'İşitme organı.',
  DUDAK: 'Ağzı çevreleyen etli kıvrım.',
  BURUN: 'Koku alma organı.',
  YANAK: 'Yüzün iki yanındaki etli bölüm.',
  NEFES: 'Solunan hava; soluk.',
  MUTLU: 'Sevinç duyan.',
  HUZUR: 'Rahatlık, iç dinginliği.',
  ÖZGÜR: 'Bağımsız, serbest.',
  BARIŞ: 'Savaşın olmadığı durum; uzlaşma.',
  SELAM: 'Karşılaşınca söylenen iyi dilek sözü.',
  DAVET: 'Birini bir yere çağırma.',
  DÜĞÜN: 'Evlenme töreni ve eğlencesi.',
  BALON: 'Hava ya da gazla şişirilen esnek torba.',
  KUKLA: 'İple ya da elle oynatılan bebek.',
  PASTA: 'Kremalı, süslü kek.',
  ÇAMUR: 'Toprakla suyun karışımı.',
  KAYAK: 'Karda kaymaya yarayan uzun tahta; bu tahtalarla yapılan spor.',
  KIZAK: 'Karda kaymak için kullanılan araç.',
  ZEBRA: 'Siyah beyaz çizgili, atgillerden hayvan.',
  PANDA: 'Siyah beyaz tüylü, bambu yiyen ayı.',
  KOALA: 'Avustralya\'da yaşayan, okaliptüs yaprağıyla beslenen keseli hayvan.',
  HOROZ: 'Tavuğun erkeği.',
  KATIR: 'At ile eşeğin çiftleşmesinden doğan hayvan.',
  ÇAKAL: 'Kurda benzeyen, ondan küçük yabani hayvan.',
  AKREP: 'Kuyruğunda zehirli iğnesi olan eklembacaklı.',
  YILAN: 'Bacaksız, sürünerek ilerleyen sürüngen.',
};

